import { generateBubbleSortSteps } from './sorting/bubbleSort'
import { generateSelectionSortSteps } from './sorting/selectionSort'
import { generateInsertionSortSteps } from './sorting/insertionSort'
import { generateLinearSearchSteps } from './searching/linearSearch'
import { generateBinarySearchSteps } from './searching/binarySearch'
import { generateBFSSteps } from './graph/bfs'
import { generateDFSSteps } from './graph/dfs'

// Standard default graph for BFS & DFS visualizations
export const defaultGraph = {
  nodes: [
    { id: 'A', label: 'A', x: 70, y: 150 },
    { id: 'B', label: 'B', x: 210, y: 70 },
    { id: 'C', label: 'C', x: 210, y: 230 },
    { id: 'D', label: 'D', x: 370, y: 70 },
    { id: 'E', label: 'E', x: 370, y: 230 },
    { id: 'F', label: 'F', x: 500, y: 150 },
  ],
  edges: [
    { from: 'A', to: 'B' },
    { from: 'A', to: 'C' },
    { from: 'B', to: 'D' },
    { from: 'B', to: 'E' },
    { from: 'C', to: 'E' },
    { from: 'D', to: 'F' },
    { from: 'E', to: 'F' },
  ],
  adjacencyList: {
    A: ['B', 'C'],
    B: ['A', 'D', 'E'],
    C: ['A', 'E'],
    D: ['B', 'F'],
    E: ['B', 'C', 'F'],
    F: ['D', 'E'],
  },
}

export const algorithmsData = [
  {
    id: 1,
    slug: 'bubble-sort',
    name: 'Bubble Sort',
    category: 'Sorting',
    difficulty: 'Easy',
    description: 'Repeatedly compares adjacent elements and swaps them if they are in the wrong order.',
    defaultArray: [29, 10, 14, 37, 13, 8, 25],
    timeComplexity: {
      best: 'O(n)',
      average: 'O(n²)',
      worst: 'O(n²)',
    },
    spaceComplexity: 'O(1) Auxiliary Space',
    realLifeAnalogy: 'Arranging students in a line by height for a class photo. You compare every two students standing next to each other and swap them if the taller one is in front, repeating until the entire line is ordered.',
    sourceCode: [
      { line: 1, text: 'function bubbleSort(arr) {' },
      { line: 2, text: '  for (let i = 0; i < arr.length - 1; i++) {' },
      { line: 3, text: '    for (let j = 0; j < arr.length - i - 1; j++) {' },
      { line: 4, text: '      if (arr[j] > arr[j + 1]) {' },
      { line: 5, text: '        swap(arr, j, j + 1);' },
      { line: 6, text: '      }' },
      { line: 7, text: '    }' },
      { line: 8, text: '  }' },
      { line: 9, text: '  return arr;' },
      { line: 10, text: '}' },
    ],
    generateSteps: (input) => generateBubbleSortSteps(input.array),
  },
  {
    id: 2,
    slug: 'selection-sort',
    name: 'Selection Sort',
    category: 'Sorting',
    difficulty: 'Easy',
    description: 'Finds the minimum element from the unsorted part and places it at the beginning of the array.',
    defaultArray: [64, 25, 12, 22, 11, 38],
    timeComplexity: {
      best: 'O(n²)',
      average: 'O(n²)',
      worst: 'O(n²)',
    },
    spaceComplexity: 'O(1) Auxiliary Space',
    realLifeAnalogy: 'Sorting a pile of books by thickness: scan the entire stack to find the thinnest book, place it on the top of your sorted pile, then scan the remaining pile for the next thinnest book.',
    sourceCode: [
      { line: 1, text: 'function selectionSort(arr) {' },
      { line: 2, text: '  for (let i = 0; i < arr.length - 1; i++) {' },
      { line: 3, text: '    let minIdx = i;' },
      { line: 4, text: '    for (let j = i + 1; j < arr.length; j++) {' },
      { line: 5, text: '      if (arr[j] < arr[minIdx]) minIdx = j;' },
      { line: 6, text: '    }' },
      { line: 7, text: '    if (minIdx !== i) swap(arr, i, minIdx);' },
      { line: 8, text: '  }' },
      { line: 9, text: '  return arr;' },
      { line: 10, text: '}' },
    ],
    generateSteps: (input) => generateSelectionSortSteps(input.array),
  },
  {
    id: 3,
    slug: 'insertion-sort',
    name: 'Insertion Sort',
    category: 'Sorting',
    difficulty: 'Easy',
    description: 'Builds the final sorted array one item at a time by repeatedly inserting elements into their correct position.',
    defaultArray: [12, 11, 13, 5, 6, 18, 9],
    timeComplexity: {
      best: 'O(n)',
      average: 'O(n²)',
      worst: 'O(n²)',
    },
    spaceComplexity: 'O(1) Auxiliary Space',
    realLifeAnalogy: 'Sorting playing cards in your hand. You take cards one by one from the deck and insert each card into its correct spot among the cards you already hold in your hand.',
    sourceCode: [
      { line: 1, text: 'function insertionSort(arr) {' },
      { line: 2, text: '  for (let i = 1; i < arr.length; i++) {' },
      { line: 3, text: '    let key = arr[i], j = i - 1;' },
      { line: 4, text: '    while (j >= 0 && arr[j] > key) {' },
      { line: 5, text: '      arr[j + 1] = arr[j];' },
      { line: 6, text: '      j = j - 1;' },
      { line: 7, text: '    }' },
      { line: 8, text: '    arr[j + 1] = key;' },
      { line: 9, text: '  }' },
      { line: 10, text: '  return arr;' },
      { line: 11, text: '}' },
    ],
    generateSteps: (input) => generateInsertionSortSteps(input.array),
  },
  {
    id: 4,
    slug: 'linear-search',
    name: 'Linear Search',
    category: 'Searching',
    difficulty: 'Easy',
    description: 'Sequentially checks each element of the list until a match is found or the whole list has been searched.',
    defaultArray: [10, 50, 30, 70, 80, 20, 90, 40],
    defaultTarget: 70,
    timeComplexity: {
      best: 'O(1)',
      average: 'O(n)',
      worst: 'O(n)',
    },
    spaceComplexity: 'O(1) Auxiliary Space',
    realLifeAnalogy: 'Searching for a specific key on an unmarked ring by trying each key one by one from left to right until you find the one that unlocks the door.',
    sourceCode: [
      { line: 1, text: 'function linearSearch(arr, target) {' },
      { line: 2, text: '  for (let i = 0; i < arr.length; i++) {' },
      { line: 3, text: '    if (arr[i] === target) {' },
      { line: 4, text: '      return i; // Target Found' },
      { line: 5, text: '    }' },
      { line: 6, text: '  }' },
      { line: 7, text: '  return -1; // Not Found' },
      { line: 8, text: '}' },
    ],
    generateSteps: (input) => generateLinearSearchSteps(input.array, input.target),
  },
  {
    id: 5,
    slug: 'binary-search',
    name: 'Binary Search',
    category: 'Searching',
    difficulty: 'Medium',
    description: 'Efficiently finds an item from a sorted list by repeatedly halving the search interval.',
    defaultArray: [4, 9, 15, 23, 38, 42, 56, 71, 88, 95],
    defaultTarget: 56,
    timeComplexity: {
      best: 'O(1)',
      average: 'O(log n)',
      worst: 'O(log n)',
    },
    spaceComplexity: 'O(1) Iterative',
    realLifeAnalogy: 'Searching for a word in a dictionary. You open directly to the middle page, determine if your word comes alphabetically before or after, and eliminate half of the remaining pages each step.',
    sourceCode: [
      { line: 1, text: 'function binarySearch(arr, target) {' },
      { line: 2, text: '  let low = 0, high = arr.length - 1;' },
      { line: 3, text: '  while (low <= high) {' },
      { line: 4, text: '    let mid = Math.floor((low + high) / 2);' },
      { line: 5, text: '    if (arr[mid] === target) return mid;' },
      { line: 6, text: '    else if (arr[mid] < target) low = mid + 1;' },
      { line: 7, text: '    else high = mid - 1;' },
      { line: 8, text: '  }' },
      { line: 9, text: '  return -1;' },
      { line: 10, text: '}' },
    ],
    generateSteps: (input) => generateBinarySearchSteps(input.array, input.target),
  },
  {
    id: 6,
    slug: 'bfs',
    name: 'Breadth First Search (BFS)',
    category: 'Graph',
    difficulty: 'Medium',
    description: 'Traverses or searches graph data structures level by level using a FIFO queue.',
    defaultStartNode: 'A',
    timeComplexity: {
      best: 'O(V + E)',
      average: 'O(V + E)',
      worst: 'O(V + E)',
    },
    spaceComplexity: 'O(V) Queue & Visited Set',
    realLifeAnalogy: 'Social networking connections (1st-degree friends, 2nd-degree friends) or ripples expanding outwards when a pebble is dropped in still water.',
    sourceCode: [
      { line: 1, text: 'function bfs(graph, start) {' },
      { line: 2, text: '  const visited = new Set([start]);' },
      { line: 3, text: '  const queue = [start];' },
      { line: 4, text: '  while (queue.length > 0) {' },
      { line: 5, text: '    const node = queue.shift();' },
      { line: 6, text: '    for (const neighbor of graph[node]) {' },
      { line: 7, text: '      if (!visited.has(neighbor)) {' },
      { line: 8, text: '        visited.add(neighbor); queue.push(neighbor);' },
      { line: 9, text: '      }' },
      { line: 10, text: '    }' },
      { line: 11, text: '  }' },
      { line: 12, text: '}' },
    ],
    generateSteps: (input) => generateBFSSteps(input.graph || defaultGraph, input.startNode || 'A'),
  },
  {
    id: 7,
    slug: 'dfs',
    name: 'Depth First Search (DFS)',
    category: 'Graph',
    difficulty: 'Medium',
    description: 'Explores as far as possible along each branch before backtracking using a stack or recursion.',
    defaultStartNode: 'A',
    timeComplexity: {
      best: 'O(V + E)',
      average: 'O(V + E)',
      worst: 'O(V + E)',
    },
    spaceComplexity: 'O(V) Call Stack & Visited Set',
    realLifeAnalogy: 'Navigating a complex labyrinth or maze. You walk straight down one pathway until you hit a dead end, then backtrack to the previous fork in the road and try another unexplored path.',
    sourceCode: [
      { line: 1, text: 'function dfs(graph, start, visited = new Set()) {' },
      { line: 2, text: '  visited.add(start);' },
      { line: 3, text: '  for (const neighbor of graph[start]) {' },
      { line: 4, text: '    if (!visited.has(neighbor)) {' },
      { line: 5, text: '      dfs(graph, neighbor, visited);' },
      { line: 6, text: '    }' },
      { line: 7, text: '  }' },
      { line: 8, text: '}' },
    ],
    generateSteps: (input) => generateDFSSteps(input.graph || defaultGraph, input.startNode || 'A'),
  },
]
